[project]
name = "toolhunch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Diego Margoni", email = "diegof.margoni@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
toolhunch = "toolhunch:main"

[build-system]
requires = ["uv_build>=0.12.4,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ipdb>=0.13.13",
    "pytest>=9.1.1",
]
